name:                two
version:             0.1.0.0
github:              "githubuser/one"
license:             BSD3
author:              "John Doneth"
maintainer:          "doneth7@gmail.com"
copyright:           "2021 John Doneth"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/JohnDoneth/advent-of-code-2020#readme>

dependencies:
- base >= 4.7 && < 5
- HUnit 
- flow
- parsec

library:
  source-dirs: src

executables:
  two-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - two

tests:
  two-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - two
