[package]
edition = "2018"
name = "day6"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.7.0"
indoc = "1.0.3"
nom = "7.0.0"
sugars = "3.0.0"

[dev-dependencies]
pretty_assertions = "0.7.2"
